### ISSUE TITLE
rocminfo dependency not specified in the debian package

### ISSUE THREAD

**Issue by whchung** [ROCm/rocprofiler#36] opened 2020-10-23 17:14 UTC
`rocprof` depends on `rocminfo` to be executed properly, but such dependency is not specified in the debian package.

Source code where the dependency to `rocminfo` takes place:
https://github.com/ROCm-Developer-Tools/rocprofiler/blob/amd-master/bin/rpl_run.sh#L205

Debian package dependency is missing:
```
$ apt show rocprofiler-dev
Package: rocprofiler-dev
Version: 1.0.0
Priority: optional
Section: devel
Maintainer: Advanced Micro Devices Inc.
Installed-Size: 1541 kB
Depends: hsa-rocr-dev
Download-Size: 254 kB
APT-Sources: http://repo.radeon.com/rocm/apt/debian xenial/main amd64 Packages
Description: ROCPROFILER library for AMD HSA runtime API extension support

N: There is 1 additional record. Please use the '-a' switch to see it
```

**Comment by harkgill-amd** [comment] 2024-07-29 18:35
Closing this ticket as https://github.com/ROCm/rocprofiler/pull/37 has already been merged and the issue is resolved.

**Closed as completed by harkgill-amd** 2024-07-29 18:35 UTC
