### ISSUE TITLE
gfx1030, metrics.xml, gfx_metrics.xml - doesn't contain descriptions.

### ISSUE THREAD

**Issue by sysmanalex** [ROCm/rocprofiler#94] opened 2022-08-11 19:11 UTC
rocprof --list-derived
Derived metrics:
ERROR: rocprofiler_iterate_info(), ImportMetrics(), Bad metric 'L2CacheHit', var 'TCC_HIT[0]' is not found.
rocm-5.1.2/rocprofiler/bin/rocprof
amdgpu-install_22.10

**Comment by sysmanalex** [comment] 2022-08-16 16:08
any updates here ? rocprofiler metrics definition & support for RDNA2 / GFX10/GFX11 ?

**Comment by dmikushin** [comment] 2022-11-21 17:07
RX 6800 is also affected by the same error.

**Comment by code-fool** [comment] 2022-11-30 02:12
6800 6900 6950 all have the same error

**Comment by code-fool** [comment] 2022-11-30 02:17
the make mytest && run.sh can only access two PASSED

**Comment by jevolk** [comment] 2022-12-05 19:55
I updated from ROCm 5.2 to 5.4 (by release-upgrading my Ubuntu 22.04 Jammy to 22.10 Kinetic) and it resolved the issue for me. Radeon V520 gfx1011 AWS G4ad.

**Comment by sysmanalex** [comment] 2022-12-06 13:39
hmm will check it later... on amd mi60/mi100.
p.s. without working opencl profiler it was too sad waste of time.
I already sold 6800/6900. now testing similar nvidia/xilinx/intel for same opencl code/optimizations.
Ubuntu 22/debian was not an issue, I was testing all drivers spectrum from amdgpu-pro-20.50 till 21.30,22.xx+ & even compile rocprofiler from sources github, too much effort.

**Comment by xenshinu** [comment] 2023-02-01 02:36
Any updates here? I met the same issue running on RX6800XT, gfx1030. I am currently running ROCm5.2 on ubuntu18.04, will upgrade to 5.4 resolve the issue?

**Comment by sysmanalex** [comment] 2023-03-16 23:50
AMD bug still not FIXED ! Bad metric 'L2CacheHit', var 'TCC_HIT[0]' is not found.

**Comment by harkgill-amd** [comment] 2024-08-16 18:40
Hi @sysmanalex, sorry for the lack of response. I was not able to reproduce this issue with the ROCm 6.2 release. I tested on a W6800 (gfx1030) machine and also a MI100 (gfx908) machine. 

There a few fixes that were introduced for this issue since this ticket was opened. Could you please confirm if you are still seeing this issue?

**Comment by harkgill-amd** [comment] 2024-09-24 16:05
@sysmanalex, closing this ticket out for now. If you are still encountering this issue, please leave a comment and I will re-open this ticket. Thanks!

**Closed as completed by harkgill-amd** 2024-09-24 16:05 UTC
