### ISSUE TITLE
rocprof -i input.txt with several pmc lines crash

### ISSUE THREAD

**Issue by yoann-heitz** [ROCm/rocprofiler#43] opened 2021-03-19 13:15 UTC
When running 
```
./rocprofiler/bin/rocprof -i input.txt --hsa-trace -d traces ./roctracer/test/MatrixTranspose/MatrixTranspose
```
with several pmc lines in the input.txt file, the program crash with a segmentation fault error after the second run of the program
```
./rocprofiler/bin/rocprof: line 271: 861977 Segmentation fault      (core dumped) "./roctracer/test/MatrixTranspose/MatrixTranspose"
```
I use rocm-4.0.0 and I cloned and built rocprofiler and roctracer from the github repositories. I used both amd-master and rocm-4.0.x branches and the error occurs in both cases.

[input_error.txt](https://github.com/ROCm-Developer-Tools/rocprofiler/files/6171306/input_error.txt)
[input.txt](https://github.com/ROCm-Developer-Tools/rocprofiler/files/6171308/input.txt)

**Comment by arfio** [comment] 2022-03-21 16:08
This issue is still happening on ROCm 5.0.0.

**Comment by harkgill-amd** [comment] 2024-08-07 18:49
Hi @yoann-heitz and @arfio, I was not able to reproduce this issue on the latest ROCm 6.2.0 release. I used the input.txt file provided with the MatrixTranspose example found [here](https://github.com/ROCm/hip-tests/blob/develop/samples/2_Cookbook/0_MatrixTranspose/MatrixTranspose.cpp). I will close this issue, if you are still encountering the segmentation fault, please open a new ticket. Thanks!

**Closed as completed by harkgill-amd** 2024-08-07 18:49 UTC
