### ISSUE TITLE
More time is spent in user mode when rocprofiler is used with MPI.

### ISSUE THREAD

**Issue by arfio** [ROCm/rocprofiler#79] opened 2022-02-25 18:50 UTC
When running an MPI program with rocprof the user time is 39% less than without it.
When looking at the Linux kernel trace with LTTng tracer, we can see that the main process for each rank is waiting half the time when rocprof is enabled and it is in running mode without it.
When synchronizing the linux kernel trace with the rocprof trace we can see, that this happens with the memory transfer calls.

In the images, blue indicates that the thread is in kernel mode, green, user mode and a yellow line means that the thread is waiting.

![withrocprof](https://user-images.githubusercontent.com/8209717/155770869-e5c3abd3-b0f2-4699-b1e9-89ea0e2501da.png)
![tracewithoutrocprof](https://user-images.githubusercontent.com/8209717/155770873-7a026b7b-a94c-40b4-8aa3-559b79800bd0.png)

**Comment by kikimych** [comment] 2022-07-01 18:56
Can't reproduce with relatively large kernel. Rocprofiler submits additional packets to hsa_queue forcing sched_yield(). There is no additional switches to kernel space.

**Comment by ppanchad-amd** [comment] 2024-08-27 18:59
@arfio Apologies for the lack of response.  Can you please check if your issue still exists with the latest ROCm 6.2? If resolved, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment] 2024-09-24 17:12
@arfio Closing ticket. Please feel free to re-open a ticket if you still see the issue with the latest ROCm. Thanks!

**Closed as not planned by ppanchad-amd** 2024-09-24 17:12 UTC
