### ISSUE TITLE
Multiple variable definition errors if rocprofiler.h is included in multiple C files

### ISSUE THREAD

**Issue by gcongiu** [ROCm/rocprofiler#114] opened 2023-05-17 10:45 UTC
The `HSA_VEN_AMD_AQLPROFILE_LEGACY_PM4_PACKET_SIZE` is defined in an header file (`hsa_ven_amd_aqlprofile.h`) instead of a C file. The header is then included in `rocprofiler.h` and causes multiple definition errors at compile time when the rocprofiler header is included in more than one C file.

A possible fix for this problem could be to define the variable as `static` in the header file or to declare it `extern` in the header and define it another C file.

**Comment by gcongiu** [comment] 2023-06-09 08:45
@ammarwa any update on this? Thanks

**Comment by gcongiu** [comment] 2023-06-12 20:20
This is a reproducer
[issue-114.tar.gz](https://github.com/ROCm-Developer-Tools/rocprofiler/files/11727985/issue-114.tar.gz)

**Comment by tcgu-amd** [comment] 2024-08-26 18:43
@gcongiu Thanks for the reproducer! I was able to reproduce the issue on ROCm-6.2. Since this issue is a duplicate of https://github.com/ROCm/ROCR-Runtime/issues/121, we will be closing this issue and track it there. Thanks!

**Closed as completed** 2024-08-26 19:00 UTC

**Comment by tcgu-amd** [comment] 2024-09-04 17:41
@mardom1 The correct usage of the header file for v2 would be that instead of '#include <rocprofiler.h>', use '#include <v2/rocprofiler.h>' instead.

Please refer to the documentation for the API here:
https://github.com/ROCm/rocprofiler?tab=readme-ov-file#rocprofiler-v1

Along with the example here:
[ROCProfilerV2 API — rocprofiler 2.0.0 Documentation (amd.com)](https://rocm.docs.amd.com/projects/rocprofiler/en/latest/reference/rocprofilerv2-api.html#kernel-profiling-1)

Apologies for the confusion. Hope this helps!
