### ISSUE TITLE
tblextr.py : bad kfd record / IndexError

### ISSUE THREAD

**Issue by yoann-heitz** [ROCm/rocprofiler#42] opened 2021-03-19 13:01 UTC
When running the following command
```
./rocprofiler/bin/rocprof --hsa-trace --hip-trace --kfd-trace -d traces python3 ./test.py
```

I sometimes get one of the following errors

```
  File "/home/yoann/rocprofiler/bin/tblextr.py", line 710, in <module>
    hip_trace_found = fill_api_db('HIP', db, indir, 'hip', HIP_PID, OPS_PID, [], {}, 1)
  File "/home/yoann/rocprofiler/bin/tblextr.py", line 441, in fill_api_db
    copy_data = list(copy_raws[copy_index])
IndexError: list index out of range
Profiling data corrupted: ' traces/rpl_data_210319_075021_860663/input_results_210319_075021/results.txt'
```
or
```
scan kfd API data 2803664:2803665                                                                                                    /home/yoann/rocprofiler/bin/tblextr.py: kfd bad record: ''
Profiling data corrupted: ' traces/rpl_data_210319_074742_860200/input_results_210319_074742/results.txt'
```

I use rocm-4.0.0 and I cloned and built rocprofiler and roctracer from the github repositories. I used both amd-master and rocm-4.0.x branches. The IndexError occurred in both cases. The kfd bad record only occurred with the rocm-4.0.0 branch (but the errors didn't occur at each run so maybe it could also occur with the amd-master branch.

[index_error.txt](https://github.com/ROCm-Developer-Tools/rocprofiler/files/6171238/index_error.txt)
[bad_record_error.txt](https://github.com/ROCm-Developer-Tools/rocprofiler/files/6171243/bad_record_error.txt)
[test.py.zip](https://github.com/ROCm-Developer-Tools/rocprofiler/files/6171244/test.py.zip)

**Comment by arfio** [comment] 2021-04-01 19:31
I get the same error using the latest 4.1 ROCm release.

**Comment by eshcherb** [comment] 2021-04-08 18:40
Could you check with '--sys-trace' which should enable HIP + HSA tracing.

**Comment by arfio** [comment] 2021-04-09 14:42
Tracing with '--sys-trace' alone works correctly.

**Comment by arfio** [comment] 2022-03-21 19:06
I am not able to reproduce this issue with the latest ROCm (5.0.0).

**Comment by harkgill-amd** [comment] 2024-08-07 18:41
Closing as issue is no longer reproducible. If you still encounter this issue with the latest ROCm 6.2.0 release, please open a new ticket. Thanks!

**Closed as completed by harkgill-amd** 2024-08-07 18:41 UTC
