### ISSUE TITLE
Tool lib failed to load.

### ISSUE THREAD

**Issue by Electricks94** [ROCm/rocprofiler#72] opened 2022-02-01 14:37 UTC
Using rocprof with ROCm v4.5 in Ubuntu gives the following problem:

```
rocprof --hsa-trace ./test
RPL: on '220201_151632' from '/opt/rocm-4.5.0/rocprofiler' in '/home'
RPL: profiling '"./test"'
RPL: input file ''
RPL: output dir '/tmp/rpl_data_220201_151632_971494'
RPL: result dir '/tmp/rpl_data_220201_151632_971494/input_results_220201_151632'
Tool lib "/opt/rocm-4.5.0/roctracer/tool/libtracer_tool.so" failed to load.
```

Is this a problem with the driver? Which driver do I need to use?

**Comment by kikimych** [comment] 2022-03-23 17:41
No, it's not driver problem. Could you check whether this file exists with correct access rules?

**Comment by harkgill-amd** [comment] 2024-08-13 20:08
Hi @Electricks94, apologies for the lack of response. A few notes on this

1. I was not able to reproduce your issue by running rocprof with the --hsa-trace flag enabled. 
2. A couple different fixes have been implemented for similar issues since you first opened this ticket. 
3. `libtracer_tool.so` has also been renamed to `libroctracer_tool.so` and moved to `/opt/rocm-6.2.0/lib/roctracer/`.

Could you please confirm if are able to reproduce this issue with ROCm 6.2.0? If so, we can continue investigating from there.

**Comment by harkgill-amd** [comment] 2024-09-24 17:28
@Electricks94, closing this ticket out. If you are still encountering issues with `libroctracer_tool.so` failing to load, please leave a comment and I will re-open this ticket.

**Closed as completed by harkgill-amd** 2024-09-24 17:28 UTC
